{{- if .Values.service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "clearlydefined.fullname" . }}-service
  labels:
    {{- include "clearlydefined.service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.service.replicaCount }}
  selector:
    matchLabels:
      {{- include "clearlydefined.service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "clearlydefined.service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clearlydefined.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.service.repository }}"
          imagePullPolicy: {{ .Values.images.service.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.service.targetPort }}
              protocol: TCP
            {{- if .Values.service.debug.enabled }}
            - name: debug
              containerPort: {{ .Values.service.debug.port }}
              protocol: TCP
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "clearlydefined.fullname" . }}-config
            - secretRef:
                name: {{ .Values.existingSecret }}
          {{- if .Values.service.debug.enabled }}
          command:
            - "node"
            - "--inspect=0.0.0.0:{{ .Values.service.debug.port }}"
            - "./bin/www"
          {{- end }}
          volumeMounts:
            - name: harvested-data
              mountPath: {{ .Values.config.fileStore.location }}
          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
      volumes:
        - name: harvested-data
          {{- if .Values.harvestedData.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "clearlydefined.fullname" . }}-harvested-data
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.service.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.service.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
