{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clearlydefined.fullname" . }}-redis
  labels:
    {{- include "clearlydefined.redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "clearlydefined.redis.selectorLabels" . | nindent 4 }}
{{- end }}
